# Generated by Django 3.0.2 on 2020-08-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_before', models.FileField(blank=True, null=True, upload_to='', verbose_name='Trash image before')),
                ('file_after', models.FileField(blank=True, null=True, upload_to='', verbose_name='Trash image after')),
                ('trash_count', models.IntegerField(default=0)),
            ],
        ),
    ]
