# Generated by Django 3.0.2 on 2020-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='url_after',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trash',
            name='url_before',
            field=models.URLField(blank=True, null=True),
        ),
    ]
