# Generated by Django 3.0.2 on 2020-08-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20200804_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='url_after',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trash',
            name='url_before',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
