# Generated by Django 3.0.2 on 2020-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_auto_20200804_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCountInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_before', models.FileField(blank=True, null=True, upload_to='', verbose_name='Trash image before')),
                ('file_after', models.FileField(blank=True, null=True, upload_to='', verbose_name='Trash image after')),
                ('url_before', models.URLField(blank=True, max_length=500, null=True)),
                ('url_after', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashCountResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_count', models.IntegerField(default=0)),
                ('trash_count_before', models.IntegerField(default=0)),
                ('trash_count_after', models.IntegerField(default=0)),
                ('image_box_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_file_name', models.FilePathField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], max_length=10, null=True)),
                ('msg', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashDetectionInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Trash image before')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashDetectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash_count', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], max_length=10, null=True)),
                ('msg', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
