# Generated by Django 3.0.2 on 2020-08-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_auto_20200814_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashdetectionresult',
            name='download_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trashdetectioninput',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Trash image'),
        ),
    ]
