# Generated by Django 3.0.2 on 2020-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_auto_20200814_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcountresult',
            name='image_box_url',
        ),
        migrations.RemoveField(
            model_name='trashcountresult',
            name='image_file_name',
        ),
        migrations.AddField(
            model_name='trashcountresult',
            name='download_link_after',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trashcountresult',
            name='download_link_before',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trashcountresult',
            name='trash_count_diff',
            field=models.IntegerField(default=0),
        ),
    ]
